### PR TITLE
Applying patch from #37

### LINKED ISSUE #37: ts-transform-paths needs updating for TypeScript 4.5+
ts-transform-paths is broken for TypeScript 4.5+.
The reason is that import declarations nodes miss `parent` node and therefore TS is unable to determine source file of node (compiler/checker.ts, `resolveExternalModule` function).

I did a quick look and apparently setting `newNode.parent` to original node `.parent` fixes it (as you have done for export declarations).
Since I heavily rely on [@zerollup/ts-transform-paths](https://github.com/zerkalica/zerollup/tree/master/packages/ts-transform-paths) in my work, I created [@Kadeluxe/ts-transform-paths](https://github.com/Kadeluxe/ts-transform-paths) repo with that fix and some other small changes.

I'm not creating PR here because I don't have much knowledge of TypeScript internals so I can't tell if it's the proper way to fix it. I guess this plugin may need further updating.

**UPDATE:** since there is no progress on this, I published my fork on NPM: https://www.npmjs.com/package/@kadeluxe/ts-transform-paths
Do `npm i @kadeluxe/ts-transform-paths` and replace `@zerollup/ts-emit-import-alias` with `@kadeluxe/ts-emit-import-alias` in your `tsconfig.json`. Now it will work.
Also you can switch to different transformer like https://github.com/LeDDGroup/typescript-transform-paths.

### PR DESCRIPTION
**Pull request by simmo**
To fix #37 

Can verify that the code in the patch mentioned in #37 resolved the issue with TypeScript 4.5.

### CODE REVIEW

**Comment by simmo** [comment]
Hi @zerkalica , is there anything else I can do to help get this complete?

**Comment by j-d-carmichael** [comment]
@zerkalica any chance of getting this PR merged in any time soon? Kind of a blocker for I imagine a few projects :)

**Comment by falkenhawk** [comment]
fwiw I published a patched version [@ovos-media/ts-transform-paths](https://www.npmjs.com/package/@ovos-media/ts-transform-paths) - feel free to use it until this PR gets merged

**Comment by kdelmonte** [comment]
I think it is possible that this project is not maintained anymore (take a look at Pulse page). @falkenhawk provided a fork. I will be using that from now on.

**Comment by RmbRT** [comment]
Use `tsc-alias` for publishing and use `paths` in the `tsconfig.json`. This package and its "fixes" are permanently broken and no longer needed. See https://github.com/perun-network/erdstall-ts-sdk for reference.

**Comment by jamesrwaugh** [comment]
@RmbRT 

Changing to `tsc-alias` worked for me, thanks!

**Comment by ghost** [comment]
I switched to https://www.npmjs.com/package/typescript-transform-paths, just had to edit the "paths" tsconfig setting, otherwise works the same just replace this abandoned plugin with that one

**Comment by simmo** [comment]
Closing as no movement in PR. Looks like there are alternatives out there.

**Pull request closed without merging**
